name: gravity
favicon: null
layout_spectrum: 0.08525906968861818
typography_spectrum: 0.021182175492867827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03128390177153051
  lightness: 0.5948079698719084
  saturation: 0.8413228916469961
  rhythmicContrast: 0.3977682397235185
purpose: []
